spring:
  mail:
    host: smtp.example.com
    port: 587
    username: test@example.com
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/reports_db
